# this is the file used to deploy on Portainer
# or other more permanent hosting solutions


services:
  myapp:
    container_name: toolbox
    image: portainer/portainer-ce
    build: .
    ports:
      - "8081:8081"
    volumes:
      - "app_data:/var/app_data"

volumes:
  app_data:
