
services:
  toolbox:
    container_name: my_toolbox_dev
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Edmonton
    restart: unless-stopped
    ports:
      - "9001:9001"
